version: '3.8'

services:

  api:
    build: 
      dockerfile: Dockerfile
      network: host
      args:
        - DB_URL=${DATABASE_URL}
    restart: always
    ports:
      - "3000:3000"
    

  api-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB$=${DB_DB} 
    ports:
      - "5433:5432"
    